### ISSUE TITLE
The \forall \epsilon' in advanced composition

### ISSUE THREAD

**Issue by SriAR** [uvm-plaid/programming-dp#12]
The [section](https://uvm-plaid.github.io/programming-dp/notebooks/ch6.html#advanced-composition) on advanced composition has a line that says:

" for \epsilon', \delta \ge 0, the total privacy cost of the entire k-fold adaptive composition is equal to \epsilon', \delta, where <formula for \epsilon'>. "

The \epsilon' should be outside the \forall quantifier right? My understanding was that the order of quantifier goes "\forall \epsilon, \delta, \exists \epsilon' given by formula", but I might be misunderstanding something. Specifically, I think the dash should be removed in the first \epsilon'.

Not as important, but I think there should be brackets around the \epsilon', \delta at the end of the sentence?

**Comment by jnear** [comment]
Our description of the theorem is based on [Dwork & Roth](https://www.cis.upenn.edu/~aaroth/Papers/privacybook.pdf), Theorem 3.20. Because we're not describing the full approximate-DP version here, I see how the wording is confusing - there's not really any need to quantify over ε' at all. We've updated the wording in the chapter to fix this.
